### PR TITLE
Replace code for depreciated componentWillMount()

### PR DESCRIPTION
**Pull request by PolarisWT**
Placed code into constructor.
Reference: https://github.com/TheRealNate/meteor-react-native/issues/4#issuecomment-626992348

### CODE REVIEW

**Comment by TheRealNate** [comment]
@PolarisWT, have you been able to do any production testing with this PR?

**Comment by PolarisWT** [comment]
I have been using it locally for development without issue for past few weeks.  Not that means it has been tested thoroughly, but I cannot determine other methods to test against other use cases.  In my use, it is solid...

I'd be happy to test more if you can provide some examples to test against.

**Comment by TheRealNate** [comment]
Hi @PolarisWT, sorry for the delay in replying. GitHub forgot to notify me about your message. The best recommendation I can make right now is building for Android and iOS in Release mode and testing on a real device.

For android, this means building a release apk (`./gradlew assembleRelease`), and for iOS this means setting the build scheme to "Release". 

A testing app (simple-todos-react-native) is being built, but isn't quite ready yet.

**Comment by PolarisWT** [comment]
With my development setup, we are testing on multiple simulated and physical (real) devices (both iOS and Android) as part of our workflow.  Using Expo which handles the bundling and generation of production ready .ipa and .apk for installs on local devices.  Again, we are not ready to publish production so they are not signed - but I haven't experienced any issues from dev testing to production just from using a signed bundle.

I was wondering if there were tests that you could determine if moving this code earlier in the Mounting lifecycle would change anything.  I haven't seen any undetermined outcomes in my usage, and plan to develop with it and deploy to production.

**Comment by TheRealNate** [comment]
Merging this into the `dev` branch so that further testing can take place.

**Comment by TheRealNate** [comment]
This has been published in beta release `2.1.0-beta1`

**Pull request merged**
