### PR TITLE
Provide useTracker function

### PR DESCRIPTION
**Pull request by sandeepjain**

### CODE REVIEW

**Comment by TheRealNate** [comment]
Hi @sandeepjain, thanks for the PR! Have you been able to test this in production?

**Comment by TheRealNate** [comment]
Hi @sandeepjain, the new [contribution guidelines](/CONTRIBUTING.md) contain our community guidelines for contributions to MeteorRN. Have you been able to test this PR against the test cases mentioned?

**Comment by TheRealNate** [comment]
Merging this into the `dev` branch so further testing can take place.

**Comment by sandeepjain** [comment]
@TheRealNate Apologies for the absence all this while as I had other priorities to take care of.

I have had a preliminary run through and this function isn't working as expected. I will try to find some time to work on the fix. In meanwhile, if someone is willing to help it would be good as well.

**Comment by TheRealNate** [comment]
Hi @sandeepjain, I've opened a new issue at #29 for tracking purposes.

**Pull request merged**
