### PR TITLE
RC: 2.1.0

### PR DESCRIPTION
**Pull request by TheRealNate**
The latest beta release of this update on NPM is `2.1.0-beta1`

**Breaking changes:**
- This release will end support for old package name `meteor-react-native`
- Support for `Meteor.collection` (lowercase-C) has been removed. Use `Mongo.Collection` (recommended) or `Meteor.Collection` (less recommended) instead

**Updates:**
- Add `useTracker`

**Bugs Fixes:**
This release fixes issues #3, #4, and #29

### CODE REVIEW

**Comment by TheRealNate** [comment]
Beta release `2.1.0-beta1` has been published, and is open for testing.

**Comment by TheRealNate** [comment]
This release will also fix #3 and #4

**Comment by TheRealNate** [comment]
Since this release affects core features of Meteor React Native (`withTracker`), we are still working on testing this release. We are eager for help from the community to test this release! **Whether you have an issue, or everything works fine, let us know your experience with this beta release.**

**Comment by mvogttech** [comment]
Any update for when this Hook will be published? I need it for a project I am trying to convert to over to Meteor.

**Comment by TheRealNate** [comment]
> Any update for when this Hook will be published? I need it for a project I am trying to convert to over to Meteor.

Hi @mvogttech, this release is still undergoing testing for release track, however you can get the new hooks capability by installing `@meteorrn/core` on the beta track.

**Comment by TheRealNate** [comment]
`2.1.0` has been marked as release candidate. You can see the full changelog on the GitHub releases page.

To install: `npm install --save @meteorrn/core@2.1.0-rc1`

**Comment by TheRealNate** [comment]
`2.1.0` will be published on NPM shortly

**Pull request merged**
